version: "3"

# Compose File meant for local testing

services:
  zookeeper:
    image: zookeeper:3.4
    ports:
      - 2181:2181
    networks:
      - kappa

  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - 9092:9092
      - 9094:9094
    hostname: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_NAME: kafka
      KAFKA_CREATE_TOPICS: "chat_message:1:1"
    networks:
      - kappa

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kappa
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - kappa
    
networks:
  kappa:
    external: true
