version: "3.4"

# Compose File meant for local testing

services:
  twitch:
    image: mattsp1290/kappa-twitch
    environment:
      KAFKA: "kafka:9092"
      KAFKA_TOPIC: "chat_message"
      TWITCH_USERNAME: $TWITCH_USERNAME
      TWITCH_PASSWORD: $TWITCH_PASSWORD
      TWITCH_CHANNEL: "dexbonus"
    networks:
      - kappa

  messages:
    image: mattsp1290/kappa-messages:latest
    networks:
      - kappa

  rails:
    image: mattsp1290/kappa-messages-rails:latest
    ports:
      - 3000:3000
    networks:
      - kappa
    
networks:
  kappa:
    external: true
